framework:
    http_client:
        scoped_clients:
            adventOfCode.client:
                base_uri: 'https://adventofcode.com/%env(ADVENT_OF_CODE_SESSION_YEAR)%/'
                headers:
                    Cookie: 'session=%env(ADVENT_OF_CODE_SESSION_ID)%'
